### ISSUE TITLE
Backticks crash textusm

### ISSUE THREAD

**Issue by jceb** [harehare/textusm#715]
I created the following document and it generates an error:
```
Action
    Task `task`
```

```
textusm -w 10024 -d user_story_map -i user-story-map.txt install build -o build/user-story-map.png
Error: Error: failed to find element matching selector "#usm"
    at ElementHandle.$eval (/home/jceb/.node_modules/textusm.cli/node_modules/puppeteer/lib/cjs/puppeteer/common/JSHandle.js:649:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Internal error.
```

**Comment by harehare** [comment]
Thank you for bug report!

**Comment by harehare** [comment]
FIx https://github.com/harehare/textusm/commit/87b79bfdc3c2362718f64f051e53258bfe6bbc72
