### ISSUE TITLE
textusm cli fails when passing a width

### ISSUE THREAD

**Issue by jceb** [harehare/textusm#734]
Version: 0.6.9

Call: `textusm -w 1024 -i x -o x.png`

Result:
```
(node:417230) UnhandledPromiseRejectionWarning: Error: Protocol error (Emulation.setDeviceMetricsOverride): Invalid pa
rameters Failed to deserialize params.width - BINDINGS: int32 value expected at position 21
    at /home/jceb/.node_modules/textusm.cli/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:208:63
    at new Promise (<anonymous>)
    at CDPSession.send (/home/jceb/.node_modules/textusm.cli/node_modules/puppeteer/lib/cjs/puppeteer/common/Connectio
n.js:207:16)
    at EmulationManager.emulateViewport (/home/jceb/.node_modules/textusm.cli/node_modules/puppeteer/lib/cjs/puppeteer
/common/EmulationManager.js:20:26)
    at Page.setViewport (/home/jceb/.node_modules/textusm.cli/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:
973:58)
    at /home/jceb/.node_modules/textusm.cli/dist/index.js:217:22
    at step (/home/jceb/.node_modules/textusm.cli/dist/index.js:34:23)
    at Object.next (/home/jceb/.node_modules/textusm.cli/dist/index.js:15:53)
    at fulfilled (/home/jceb/.node_modules/textusm.cli/dist/index.js:6:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:417230) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing
inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To t
erminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https:
//nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:417230) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise reject
ions that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by harehare** [comment]
Fix https://github.com/harehare/textusm/commit/6ee42bb79e173e549ba153fd1eb38c6b7fcdc16c
